---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: thebino

---

**🐛 Describe the bug**
  
  A clear and concise description of what happened.
  
  **💥 When did the bug occurred.***
- [ ] Installation / First-run
- [ ] Configuration
- [ ] Other
  
  **👣 To Reproduce**

Steps to reproduce the behavior:
  1. Go to '...'
  2. Click on '....'
  3. Scroll down to '....'
  4. See error
  
  
  **🧐 Expected behavior**
  
  A clear and concise description of what you expected to happen.
  
  **💻 Versions (please complete the following information):**

- OS: [e.g. macOS Venture 13.0]
- Device: [e.g. Bookii v1.0]
