name: Continuous Delivery Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'art/**'
      - '*.md'
    types: [opened, synchronize, reopened, edited]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: true

  build:
    needs: release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'

      - name: Build all
        run: |
          ./gradlew --console=plain :app-desktop:

      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ matrix.os }}
          files: |
            build/compose/binaries/main/msi/*          

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: output/test/code-coverage.html

  artifacts:
    needs: [release, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2

      - name: Display structure of downloaded files
        run: ls -R

      - name: Upload to Release
        uses: meeDamian/github-release@2
        with:
          files: >
            linux
            mac
            windows      
